// --------------------- TEAM DATA STARTS HERE --------------------- //

var teamData = [
  {
    id: 0,
    teamFullName: "Gujarat Titan",
    sName: "GT",
    fullSname: "GT (Gujarat Tistan)",
    teamIcon:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/GT/Logos/Roundbig/GTroundbig.png",
    teamLogo:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/GT/Logos/Logooutline/GToutline.png",
    WonCount: 1,
  },
  {
    id: 1,
    teamFullName: "Mumbai Indians",
    sName: "MI",
    fullSname: "MI (Mumbai Indians)",
    teamIcon:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/MI/Logos/Roundbig/MIroundbig.png",
    teamLogo:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/MI/Logos/Logooutline/MIoutline.png",
    WonCount: 5,
  },
  {
    id: 2,
    teamFullName: "Kolkata Knight Riders",
    sName: "KKR",
    fullSname: "KKR (Kolkata Knight Riders)",
    teamIcon:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/KKR/Logos/Roundbig/KKRroundbig.png",
    teamLogo:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/KKR/Logos/Logooutline/KKRoutline.png",
    WonCount: 2,
  },
  {
    id: 3,
    teamFullName: "Chennai Super Kings",
    sName: "CSK",
    fullSname: "CSK (Chennai Super King)",
    teamIcon:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/CSK/logos/Roundbig/CSKroundbig.png",
    teamLogo:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/CSK/logos/Logooutline/CSKoutline.png",
    WonCount: 5,
  },

  {
    id: 4,
    teamFullName: "Lucknow Super Giants",
    sName: "LSG",
    fullSname: "LSG (Lucknow Super Giants)",
    teamIcon:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/LSG/Logos/Roundbig/LSGroundbig.png",
    teamLogo:
      "https://feeds-100mb.s3-ap-southeast-1.amazonaws.com/teamLogos/ADAMetmKk61682948573LSG.png",
    WonCount: 0,
  },

  {
    id: 5,
    teamFullName: "Delhi Capitals",
    sName: "DC",
    fullSname: "DC (Delhi Capitals)",
    teamIcon:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/DC/Logos/Roundbig/DCroundbig.png",
    teamLogo:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/DC/Logos/LogoOutline/DCoutline.png",
    WonCount: 0,
  },
  {
    id: 6,
    teamFullName: "Royal Challengers Bangalore",
    sName: "RCB",
    fullSname: "RCB (Royal challengers Bangalore)",
    teamIcon:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/RCB/Logos/Roundbig/RCBroundbig.png",
    teamLogo:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/RCB/Logos/Logooutline/RCBoutline.png",
    WonCount: 0,
  },
  {
    id: 7,
    teamFullName: "Rajasthan Royals",
    sName: "RR",
    fullSname: "RR (Rajasthan Royals)",
    teamIcon:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/RR/Logos/Roundbig/RRroundbig.png",
    teamLogo:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/RR/Logos/Logooutline/RRoutline.png",
    WonCount: 1,
  },
  {
    id: 8,
    teamFullName: "Sunrises Hyderabad",
    sName: "SH",
    fullSname: "SH (Sunrises Hyderabad)",
    teamIcon:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/SRH/Logos/Roundbig/SRHroundbig.png",
    teamLogo:
      "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/SRH/Logos/Logooutline/SRHoutline.png",
    WonCount: 1,
  },
];

// --------------------- TEAM DATA ENDS HERE --------------------- //

// --------------------- PLAYER DATA STARTS HERE --------------------- //

var playerData = [
  //GT team
  {
    id: 0,
    playerName: "Shubham Gill",
    from: "GT",
    price: "7 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3761.png",
    playerTeam: "Gujarat Titan",
  },
  {
    id: 1,
    playerName: "Hardik Pandya",
    from: "GT",
    price: "15 Cr",
    isPlaying: true,
    description: "All-rounder",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/2740.png",
    playerTeam: "Gujarat Titan",
  },
  {
    id: 2,
    playerName: "David Miller",
    from: "GT",
    price: "3 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/128.png",
    playerTeam: "Gujarat Titan",
  },
  {
    id: 3,
    playerName: "Mathew Wade",
    from: "GT",
    price: "2.50 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/549.png",
    playerTeam: "Gujarat Titan",
  },
  {
    id: 4,
    playerName: "Mohammad Shami",
    from: "GT",
    price: "6.25 Cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/94.png",
    playerTeam: "Gujarat Titan",
  },
  {
    id: 5,
    playerName: "Dasun Shanaka",
    from: "GT",
    price: "0.20 Cr",
    isPlaying: false,
    description: "All-rounder",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/375.png",
    playerTeam: "Gujarat Titan",
  },
  {
    id: 6,
    playerName: "Rahul Tewatia",
    from: "GT",
    price: "2.00 Cr",
    isPlaying: true,
    description: "All-rounder",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/120.png",
    playerTeam: "Gujarat Titan",
  },
  {
    id: 7,
    playerName: "Rashid Khan",
    from: "GT",
    price: "15 Cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/2885.png",
    playerTeam: "Gujarat Titan",
  },
  // MI team
  {
    id: 8,
    playerName: "Suryakumar Yadav",
    from: "MI",
    price: "8 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/174.png",
    playerTeam: "Mumbai Indians",
  },
  {
    id: 9,
    playerName: "Rohit Sharma",
    from: "MI",
    price: "16 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/107.png",
    playerTeam: "Mumbai Indians",
  },
  {
    id: 10,
    playerName: "Ishan Kishan",
    from: "MI",
    price: "15.25 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/2975.png",
    playerTeam: "Mumbai Indians",
  },
  {
    id: 11,
    playerName: "Tim David",
    from: "MI",
    price: "8.25 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/636.png",
    playerTeam: "Mumbai Indians",
  },
  {
    id: 12,
    playerName: "Jasprit Bumrah",
    from: "MI",
    price: "7.50 Cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1124.png",
    playerTeam: "Mumbai Indians",
  },
  {
    id: 13,
    playerName: "Jofra Archer",
    from: "MI",
    price: "8 Cr",
    isPlaying: true,
    description: "bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/181.png",
    playerTeam: "Mumbai Indians",
  },
  {
    id: 14,
    playerName: "Arjun Tendulkar",
    from: "MI",
    price: "0.30 Cr",
    isPlaying: false,
    description: "Bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/585.png",
    playerTeam: "Mumbai Indians",
  },
  {
    id: 15,
    playerName: "Jhye Richardson",
    from: "MI",
    price: "5 Cr",
    isPlaying: true,
    description: "bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/59.png",
    playerTeam: "Mumbai Indians",
  },
  //Kkr team
  {
    id: 16,
    playerName: "Andre Russell",
    from: "KKR",
    price: "12 Cr",
    isPlaying: true,
    description: "All-rounder",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/141.png",
    playerTeam: "Kolkata Knight Riders",
  },
  {
    id: 17,
    playerName: "Venkatesh Iyer",
    from: "KKR",
    price: "8 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/584.png",
    playerTeam: "Kolkata Knight Riders",
  },
  {
    id: 18,
    playerName: "Shreyas Iyer",
    from: "KKR",
    price: "12.25 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1563.png",
    playerTeam: "Kolkata Knight Riders",
  },
  {
    id: 19,
    playerName: "Nitish Rana ",
    from: "KKR",
    price: "8 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/148.png",
    playerTeam: "Kolkata Knight Riders",
  },
  {
    id: 20,
    playerName: "Pat Cummins",
    from: "KKR",
    price: "10 Cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/488.png",
    playerTeam: "Kolkata Knight Riders",
  },
  {
    id: 21,
    playerName: "Shardul Thakur",
    from: "KKR",
    price: "10.75 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/105.png",
    playerTeam: "Kolkata Knight Riders",
  },
  {
    id: 22,
    playerName: "Rinku Singh",
    from: "KKR",
    price: "0.55 Cr",
    isPlaying: true,
    description: "All-rounder",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3830.png",
    playerTeam: "Kolkata Knight Riders",
  },
  {
    id: 23,
    playerName: "Sunil Narine",
    from: "KKR",
    price: "6 Cr",
    isPlaying: true,
    description: "All-rounder",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/156.png",
    playerTeam: "Kolkata Knight Riders",
  },

  //CSK team
  {
    id: 24,
    playerName: "MS Dhoni",
    from: "CSK",
    price: "12 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/1.png",
    playerTeam: "Chennai Super Kings",
  },
  {
    id: 25,
    playerName: "Shivam Dube",
    from: "CSK",
    price: "4 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/5431.png",
    playerTeam: "Chennai Super Kings",
  },
  {
    id: 26,
    playerName: "Robin Uthappa",
    from: "CSK",
    price: "2.50 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/127.png",
    playerTeam: "Chennai Super Kings",
  },
  {
    id: 27,
    playerName: "Dwayne Bravo",
    from: "CSK",
    price: "7.50 Cr",
    isPlaying: true,
    description: "All-rounder",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/25.png",
    playerTeam: "Chennai Super Kings",
  },
  {
    id: 28,
    playerName: "Ambati Raydu",
    from: "CSK",
    price: "6.75 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/100.png",
    playerTeam: "Chennai Super Kings",
  },
  {
    id: 29,
    playerName: "Ravindra Jadega",
    from: "CSK",
    price: "16 Cr",
    isPlaying: true,
    description: "All-rounder",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/46.png",
    playerTeam: "Chennai Super Kings",
  },
  {
    id: 30,
    playerName: "Deepak chahar",
    from: "CSK",
    price: "14 Cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/91.png",
    playerTeam: "Chennai Super Kings",
  },
  {
    id: 31,
    playerName: "Ben Stokes",
    from: "CSK",
    price: "16.25 Cr",
    isPlaying: true,
    description: "All-Rounder",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/177.png",
    playerTeam: "Chennai Super Kings",
  },
  
  //LSG team
  {
    id: 32,
    playerName: "KL rahul",
    from: "LSG",
    price: "17 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/19.png",
    playerTeam: "Lucknow Super Giants",
  },
  {
    id: 33,
    playerName: "Quinton De Cock",
    from: "LSG",
    price: "6.75 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/170.png",
    playerTeam: "Lucknow Super Giants",
  },
  {
    id: 34,
    playerName: "Nicolas Pooran",
    from: "LSG",
    price: "5.50 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/136.png",
    playerTeam: "Lucknow Super Giants",
  },
  {
    id: 35,
    playerName: "Marcus Stoinis",
    from: "LSG",
    price: "9.20 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/23.png",
    playerTeam: "Lucknow Super Giants",
  },
  {
    id: 36,
    playerName: "Krunal pandya",
    from: "LSG",
    price: "8.25 Cr",
    isPlaying: false,
    description: "All-Rounder",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/17.png",
    playerTeam: "Lucknow Super Giants",
  },
  {
    id: 37,
    playerName: "Mark wood",
    from: "LSG",
    price: "5.50 Cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/315.png",
    playerTeam: "Lucknow Super Giants",
  },
  {
    id: 38,
    playerName: "Ravi Bishnoi",
    from: "LSG",
    price: "4 Cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/520.png",
    playerTeam: "Lucknow Super Giants",
  },
  {
    id: 39,
    playerName: "Amit Mishra",
    from: "LSG",
    price: "0.50 Cr",
    isPlaying: false,
    description: "Bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/107.png",
    playerTeam: "Lucknow Super Giants",
  },

  //DC team
  {
    id: 40,
    playerName: "David Warner",
    from: "DC",
    price: "6.25 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/214.png",
    playerTeam: "Delhi Capitals",
  },
  {
    id: 41,
    playerName: "Rishabh Pant",
    from: "DC",
    price: "13.50 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/2972.png",
    playerTeam: "Delhi Capitals",
  },
  {
    id: 42,
    playerName: "Prithvi shaw",
    from: "DC",
    price: "7.50 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3764.png",
    playerTeam: "Delhi Capitals",
  },
  {
    id: 43,
    playerName: "Mandeep Singh",
    from: "DC",
    price: "1.50 Cr",
    isPlaying: false,
    description: "Batsman",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/72.png",
    playerTeam: "Delhi Capitals",
  },
  {
    id: 44,
    playerName: "Axar Patel",
    from: "DC",
    price: "9 Cr",
    isPlaying: true,
    description: "All-Rounder",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/110.png",
    playerTeam: "Delhi Capitals",
  },
  {
    id: 45,
    playerName: "Ishant Sharma",
    from: "DC",
    price: "0.50 Cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/50.png",
    playerTeam: "Delhi Capitals",
  },
  {
    id: 46,
    playerName: "Kuldeep Yadav",
    from: "DC",
    price: "2 Cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/14.png",
    playerTeam: "Delhi Capitals",
  },
  {
    id: 47,
    playerName: "Lungi Ngidi",
    from: "DC",
    price: "0.50 Cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/99.png",
    playerTeam: "Delhi Capitals",
  },

  //Rcb team
  {
    id: 48,
    playerName: "Virat Kohli",
    from: "RCB",
    price: "15 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/164.png",
    playerTeam: "Royal Challengers Bangalore",
  },
  {
    id: 49,
    playerName: "Faf Du Plesis",
    from: "RCB",
    price: "7 cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/94.png",
    playerTeam: "Royal Challengers Bangalore",
  },
  {
    id: 50,
    playerName: "Glenn Maxwell",
    from: "RCB",
    price: "11 cr",
    isPlaying: true,
    description: "All-Rounder",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/28.png",
    playerTeam: "Royal Challengers Bangalore",
  },
  {
    id: 51,
    playerName: "Dinesh Kartik",
    from: "RCB",
    price: "5.5.00cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/102.png",
    playerTeam: "Royal Challengers Bangalore",
  },
  {
    id: 52,
    playerName: "Mohammed Siraj",
    from: "RCB",
    price: "7 cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3840.png",
    playerTeam: "Royal Challengers Bangalore",
  },
  {
    id: 53,
    playerName: "Harshal Patel",
    from: "RCB",
    price: "10.75 cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/13803.png",
    playerTeam: "Royal Challengers Bangalore",
  },
  {
    id: 54,
    playerName: "Wanindu hasaranga",
    from: "RCB",
    price: "10.75 cr",
    isPlaying: false,
    description: "Bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/377.png",
    playerTeam: "Royal Challengers Bangalore",
  },
  {
    id: 55,
    playerName: "Karn Sharma",
    from: "RCB",
    price: "0.50 cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/98.png",
    playerTeam: "Royal Challengers Bangalore",
  },

  //RR team
  {
    id: 56,
    playerName: "Sanju Samson",
    from: "RR",
    price: "14 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/190.png",
    playerTeam: "Rajasthan Royals",
  },
  {
    id: 57,
    playerName: "Jos Buttler",
    from: "RR",
    price: "10 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/509.png",
    playerTeam: "Rajasthan Royals",
  },
  {
    id: 58,
    playerName: "Shimron Hetymer",
    from: "RR",
    price: "8.50 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/210.png",
    playerTeam: "Rajasthan Royals",
  },
  {
    id: 59,
    playerName: "Joe Root",
    from: "RR",
    price: "1 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/312.png",
    playerTeam: "Rajasthan Royals",
  },
  {
    id: 60,
    playerName: "Devdutt Paddikal",
    from: "RR",
    price: "7.75 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/5430.png",
    playerTeam: "Rajasthan Royals",
  },
  {
    id: 61,
    playerName: "Navdeep Saini",
    from: "RR",
    price: "2.60 Cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/207.png",
    playerTeam: "Rajasthan Royals",
  },
  {
    id: 62,
    playerName: "Adam Zampa",
    from: "RR",
    price: "1.50 Cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/24.png",
    playerTeam: "Rajasthan Royals",
  },
  {
    id: 63,
    playerName: "Jason Holder",
    from: "RR",
    price: "5.75 Cr",
    isPlaying: true,
    description: "All-Rounder",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/263.png",
    playerTeam: "Rajasthan Royals",
  },

  //SH team
  {
    id: 64,
    playerName: "Heinrich Klaasen",
    from: "SH",
    price: "6.50 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/202.png",
    playerTeam: "Sunrises Hyderabad",
  },
  {
    id: 65,
    playerName: "Rahul Tripathi",
    from: "SH",
    price: "8.50 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://assets.iplt20.com/ipl/IPLHeadshot2022/3838.png",
    playerTeam: "Sunrises Hyderabad",
  },
  {
    id: 66,
    playerName: "Mayank Agarwal",
    from: "SH",
    price: "2 Cr",
    isPlaying: false,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/55.png",
    playerTeam: "Sunrises Hyderabad",
  },
  {
    id: 67,
    playerName: "Harry brook",
    from: "SH",
    price: "13.25 Cr",
    isPlaying: true,
    description: "Batsman",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/1218.png",
    playerTeam: "Sunrises Hyderabad",
  },
  {
    id: 68,
    playerName: "Washington Sundar",
    from: "SH",
    price: "8.75 Cr",
    isPlaying: false,
    description: "All-rounder",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/20.png",
    playerTeam: "Sunrises Hyderabad",
  },
  {
    id: 69,
    playerName: "Bhuvneshwar Kumar",
    from: "SH",
    price: "4.20 Cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/15.png",
    playerTeam: "Sunrises Hyderabad",
  },
  {
    id: 70,
    playerName: "Kartik Tyagi",
    from: "SH",
    price: "4 Cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/536.png",
    playerTeam: "Sunrises Hyderabad",
  },
  {
    id: 71,
    playerName: "T Natarajan",
    from: "SH",
    price: "4 Cr",
    isPlaying: true,
    description: "Bowler",
    playerImg: "https://bcciplayerimages.s3.ap-south-1.amazonaws.com/ipl/IPLHeadshot2023/224.png",
    playerTeam: "Sunrises Hyderabad",
  },
];

// --------------------- PLAYER DATA ENDS HERE --------------------- //
